stages:
  - build
  - test
  - security
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: "$CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME"

cache:
  paths:
    - node_modules/

before_script:
  - echo "Setting up Docker environment"
  - curl -fsSL https://get.docker.com/ | sh
  - docker version

build:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t $IMAGE_TAG .
  tags:
    - docker

test:
  stage: test
  script:
    - echo "Running tests..."
    - npm install
    - npm test
  tags:
    - docker

security:
  stage: security
  script:
    - echo "Running security scans..."
    - npm audit --audit-level=high
    - npx snyk test || true
    - trivy image $IMAGE_TAG
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - echo "Deploying to test environment..."
    - docker-compose -f docker-compose.yml up -d
  only:
    - main
  tags:
    - docker
